In [96]:
import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.express as px
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [97]:
 #sklearn preproc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer, make_column_transformer, make_column_selector
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import RobustScaler, OneHotEncoder, OrdinalEncoder
from sklearn.metrics import make_scorer

from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import RandomForestRegressor

In [98]:
# Vacination Dataset
url_vaccination = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv'
url_ages = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations-by-age-group.csv'

# Index URLs
url_index_strigency = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/stringency_index_avg.csv'
url_index_gov_response = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/government_response_index_avg.csv'
url_index_health = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/containment_health_index_avg.csv'
url_index_economic = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/economic_support_index.csv'

# Indicators URLs
# C sub-indicators
url_c1 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c1m_school_closing.csv'
url_c2 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c2m_workplace_closing.csv'
url_c3 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c3m_cancel_public_events.csv'
url_c4 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c4m_restrictions_on_gatherings.csv'
url_c5 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c5m_close_public_transport.csv'
url_c6 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c6m_stay_at_home_requirements.csv'
url_c7 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c7m_movementrestrictions.csv'
url_c8 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c8ev_internationaltravel.csv'

# E sub-indicators
url_e1 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/e1_income_support.csv'
url_e2 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/e2_debtrelief.csv'

# H sub-indicators
url_h1 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/h1_public_information_campaigns.csv'
url_h2 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/h2_testing_policy.csv'
url_h3 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/h3_contact_tracing.csv'
url_h6 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/h6m_facial_coverings.csv'
url_h7 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/h7_vaccination_policy.csv'
url_h8 = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/h8m_protection_of_elderly_ppl.csv'

# Target URLs
url_cases = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/confirmed_cases.csv'
url_deaths = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/confirmed_deaths.csv'

In [99]:
# DataFrame Index
df_strigency_raw = pd.read_csv(url_index_strigency)
df_gov_response_raw = pd.read_csv(url_index_gov_response)
df_health_raw = pd.read_csv(url_index_health)
df_economic_raw = pd.read_csv(url_index_economic)

# DataFrame Vaccination
df_vaccination_raw = pd.read_csv(url_vaccination)
df_ages_raw = pd.read_csv(url_ages)

df_c1_raw = pd.read_csv(url_c1)
df_c2_raw = pd.read_csv(url_c2)
df_c3_raw = pd.read_csv(url_c3)
df_c4_raw = pd.read_csv(url_c4)
df_c5_raw = pd.read_csv(url_c5)
df_c6_raw = pd.read_csv(url_c6)
df_c7_raw = pd.read_csv(url_c7)
df_c8_raw = pd.read_csv(url_c8)

df_e1_raw = pd.read_csv(url_e1)
df_e2_raw = pd.read_csv(url_e2)

df_h1_raw = pd.read_csv(url_h1)
df_h2_raw = pd.read_csv(url_h2)
df_h3_raw = pd.read_csv(url_h3)
df_h6_raw = pd.read_csv(url_h6)
df_h7_raw = pd.read_csv(url_h7)
df_h8_raw = pd.read_csv(url_h8)


# Data Frame target
df_cases_raw = pd.read_csv(url_cases)
df_deaths_raw = pd.read_csv(url_deaths)

In [101]:
df_cases_raw['country_code']

0      ABW
1      AFG
2      AGO
3      ALB
4      AND
      ...
258    VUT
259    YEM
260    ZAF
261    ZMB
262    ZWE
Name: country_code, Length: 263, dtype: object

In [102]:
df_cases_raw[df_cases_raw['country_name']=='United Kingdom']

,Unnamed: 0,country_code,country_name,region_code,region_name,jurisdiction,01Jan2020,02Jan2020,03Jan2020,04Jan2020,...,30Aug2022,31Aug2022,01Sep2022,02Sep2022,03Sep2022,04Sep2022,05Sep2022,06Sep2022,07Sep2022,08Sep2022
82,83,GBR,United Kingdom,NaN,NaN,NAT_TOTAL,NaN,NaN,NaN,NaN,...,23492875.0,23521792.0,23521792.0,23521792.0,23521792.0,23521792.0,23521792.0,23521792.0,23521792.0,23521792.0
83,84,GBR,United Kingdom,UK_ENG,England,STATE_TOTAL,NaN,NaN,NaN,NaN,...,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0
84,85,GBR,United Kingdom,UK_NIR,Northern Ireland,STATE_TOTAL,NaN,NaN,NaN,NaN,...,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0
85,86,GBR,United Kingdom,UK_SCO,Scotland,STATE_TOTAL,NaN,NaN,NaN,NaN,...,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0
86,87,GBR,United Kingdom,UK_WAL,Wales,STATE_TOTAL,NaN,NaN,NaN,NaN,...,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0,19833314.0

In [103]:
def data_cleaning_all_index(name_data_table):
    trans_table=name_data_table.groupby('country_code').sum().T.drop('Unnamed: 0')
    trans_table.index = pd.to_datetime(trans_table.index)
    return trans_table

In [104]:
def data_cleaning_all_indicator(name_data_table):
    trans_table=name_data_table.groupby('country_code').mean().round(decimals = 0).T.drop('Unnamed: 0')
    trans_table.index = pd.to_datetime( trans_table.index)
    return trans_table

In [106]:
df_vaccination_raw

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million,daily_people_vaccinated,daily_people_vaccinated_per_hundred
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125641,Zimbabwe,ZWE,2022-08-23,NaN,NaN,NaN,NaN,NaN,6463.0,NaN,NaN,NaN,NaN,404.0,1624.0,0.010
125642,Zimbabwe,ZWE,2022-08-24,12121226.0,6404253.0,4719303.0,997670.0,NaN,5677.0,75.79,40.04,29.51,6.24,355.0,1262.0,0.008
125643,Zimbabwe,ZWE,2022-08-25,12133385.0,6407937.0,4722200.0,1003248.0,12159.0,6748.0,75.86,40.07,29.53,6.27,422.0,1637.0,0.010
125644,Zimbabwe,ZWE,2022-08-26,NaN,NaN,NaN,NaN,NaN,6434.0,NaN,NaN,NaN,NaN,402.0,1624.0,0.010
125645,Zimbabwe,ZWE,2022-08-27,12145591.0,6411006.0,4725099.0,1009486.0,NaN,6043.0,75.94,40.09,29.54,6.31,378.0,1534.0,0.010

In [107]:
df_vaccination_raw.columns

Index(['location', 'iso_code', 'date', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'daily_vaccinations_raw', 'daily_vaccinations',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'daily_vaccinations_per_million', 'daily_people_vaccinated',
       'daily_people_vaccinated_per_hundred'],
      dtype='object')

In [108]:
df_strigency = data_cleaning_all_index(df_strigency_raw)
df_gov_response = data_cleaning_all_index(df_gov_response_raw)
df_health= data_cleaning_all_index(df_health_raw)
df_economic= data_cleaning_all_index(df_economic_raw)


# DataFrames Indicator
df_c1 = data_cleaning_all_indicator(df_c1_raw)
df_c2 = data_cleaning_all_indicator(df_c2_raw)
df_c3 = data_cleaning_all_indicator(df_c3_raw)
df_c4 = data_cleaning_all_indicator(df_c4_raw)
df_c5 = data_cleaning_all_indicator(df_c5_raw)
df_c6 = data_cleaning_all_indicator(df_c6_raw)
df_c7 = data_cleaning_all_indicator(df_c6_raw)
df_c8 = data_cleaning_all_indicator(df_c7_raw)

df_e1 =data_cleaning_all_indicator(df_e1_raw)
df_e2 = data_cleaning_all_indicator(df_e2_raw)

df_h1 = data_cleaning_all_indicator(df_h1_raw)
df_h2 = data_cleaning_all_indicator(df_h2_raw)
df_h3 = data_cleaning_all_indicator(df_h3_raw)
df_h6 = data_cleaning_all_indicator(df_h6_raw)
df_h7 = data_cleaning_all_indicator(df_h7_raw)
df_h8 =data_cleaning_all_indicator(df_h8_raw)


# Data Frame target
df_cases =data_cleaning_all_index(df_cases_raw)
df_deaths = data_cleaning_all_index(df_deaths_raw)

# Cleaning Vaccination Features
df_vaccination = df_vaccination_raw.copy()
df_vaccination = df_vaccination[['date','iso_code','total_vaccinations', 'people_vaccinated','people_fully_vaccinated', 'total_boosters']]
df_vaccination=df_vaccination.set_index('date')
#df_vaccination = pd.to_datetime( df_vaccination.index)

#df_vaccination.rename(columns = {'iso_code': 'country_code'}, inplace = True)
df_vaccination.index = pd.to_datetime( df_vaccination.index)
df_vaccination.head()

,iso_code,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters
date,,,,,
2021-02-22,AFG,0.0,0.0,NaN,NaN
2021-02-23,AFG,NaN,NaN,NaN,NaN
2021-02-24,AFG,NaN,NaN,NaN,NaN
2021-02-25,AFG,NaN,NaN,NaN,NaN
2021-02-26,AFG,NaN,NaN,NaN,NaN

In [111]:
country = 'USA'

def country_output(country):
    df_gov_response_usa=df_gov_response[country]
    country_index=df_gov_response_usa
    country_index=pd.DataFrame(country_index)
    country_index.columns = ['gov_response']
    country_index.insert(0, 'containment_and_health', df_health[country])
    country_index.insert(1, 'stringency', df_strigency[country])
    country_index.insert(2,'economics_sup',df_economic[country])
    country_index.insert(3,'total_cases',df_cases[country])
    country_index.insert(4,'new_cases',df_cases[country]-df_cases[country].shift(1))
    country_index.insert(5,'total_deaths',df_deaths[country])
    country_index.insert(6,'new_deaths',df_deaths[country] - df_deaths[country].shift(1))
    country_index.index.name='date'
    country_index['new_cases'].loc[country_index['new_cases'] < 0] = 0
    country_index['new_deaths'].loc[country_index['new_deaths'] < 0] = 0
    country_index['gov_response'] = (country_index['gov_response'] / country_index['gov_response'].sum()) * 100
    country_index['containment_and_health'] = (country_index['containment_and_health'] / country_index['containment_and_health'].sum()) * 100
    country_index['stringency'] = (country_index['stringency'] / country_index['stringency'].sum()) * 100
    country_index['economics_sup'] = (country_index['economics_sup'] / country_index['economics_sup'].sum()) * 100
    country_index['economics_sup'] = (country_index['economics_sup'] / country_index['stringency'].sum()) * 100
    
    
    
    
    #vaccination
    country_vaccination=df_vaccination[df_vaccination['iso_code']==country]
    country_vaccination=country_vaccination[['total_vaccinations', 'people_vaccinated','people_fully_vaccinated', 'total_boosters']]
    
    #indicator
    df_c2_usa=df_c2[country]
    country_indicator= df_c2_usa
    country_indicator=pd.DataFrame(country_indicator)
    country_indicator.columns = ['workplace_closing']
    country_indicator.insert(0, 'cancel_public_events', df_c3[country])
    country_indicator.insert(1, 'school_closing', df_c1[country])
    country_indicator.insert(2, 'restrictions_on_gathering', df_c4[country])
    country_indicator.insert(3,'close_public_transport',df_c5[country])
    country_indicator.insert(4,'stay_at_home_requirements',df_c6[country])
    country_indicator.insert(5,'restrictions_on_internal_movement',df_c7[country])
    country_indicator.insert(6,'international_travel_controls',df_c8[country])
    country_indicator.insert(7,'income_support',df_e1[country])
    country_indicator.insert(8,'debt/contract_relief',df_e2[country])
    country_indicator.insert(9,'public_information_campaigns',df_h1[country])
    country_indicator.insert(10,'testing_policy',df_h2[country])
    country_indicator.insert(11,'contact_tracing',df_h3[country])
    country_indicator.insert(12,'facial_coverings',df_h6[country])
    country_indicator.insert(13,'vaccination_policy',df_h7[country])
    country_indicator.insert(14,'protection_of_elderly_people',df_h8[country])
    country_indicator.insert(15,'total_cases',df_cases[country])
    country_indicator.insert(16,'new_cases',df_cases[country]-df_cases[country].shift(1))
    country_indicator.insert(17,'total_deaths',df_deaths[country])
    country_indicator.insert(18,'new_deaths',df_deaths[country] - df_deaths[country].shift(1))
    country_indicator.index.name='date'
    country_indicator['new_cases'].loc[country_indicator['new_cases'] < 0] = 0
    country_indicator['new_deaths'].loc[country_indicator['new_deaths'] < 0] = 0
    
    
    country_index = country_index.merge(country_vaccination, how = 'left' , on = 'date')
    country_indicator=country_indicator.merge(country_vaccination, how = 'left' , on = 'date')
 
    
    indicator_death=country_indicator[country_indicator['total_deaths']>0]
    first_death_date=indicator_death.index[0]
    last_death_date=indicator_death.index[-1]
    country_indicator=country_indicator[~(country_indicator.index < first_death_date)]
    country_indicator=country_indicator[~(country_indicator.index > last_death_date)]
    
    index_death=country_index[country_index['total_deaths']>0]
    first_death_date_index=index_death.index[0]
    last_death_date_index=index_death.index[-1]
    country_index=country_index[~(country_index.index < first_death_date_index)]
    country_index=country_index[~(country_index.index > last_death_date_index)]
    
    country_indicator = country_indicator.fillna(0)
    country_index = country_index.fillna(0)
    
    
    
    
    return country_index,country_indicator

In [113]:
#if you want data with incator
country_indicator_United_Kingdom=country_output('GBR')[1]

In [114]:
country_index_United_Kingdom=country_output('GBR')[0]
country_index_United_Kingdom.head()

,containment_and_health,stringency,economics_sup,total_cases,new_cases,total_deaths,new_deaths,gov_response,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters
date,,,,,,,,,,,,
2020-01-30,0.005077,0.005029,0.0,4.0,4.0,1.0,1.0,0.010337,0.0,0.0,0.0,0.0
2020-01-31,0.011938,0.006281,0.0,6.0,2.0,1.0,0.0,0.023356,0.0,0.0,0.0,0.0
2020-02-01,0.011938,0.006281,0.0,6.0,0.0,1.0,0.0,0.023356,0.0,0.0,0.0,0.0
2020-02-02,0.014224,0.010048,0.0,10.0,4.0,2.0,1.0,0.028928,0.0,0.0,0.0,0.0
2020-02-03,0.014224,0.010048,0.0,88.0,78.0,2.0,0.0,0.028928,0.0,0.0,0.0,0.0

In [115]:
country_index_United_Kingdom

,containment_and_health,stringency,economics_sup,total_cases,new_cases,total_deaths,new_deaths,gov_response,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters
date,,,,,,,,,,,,
2020-01-30,0.005077,0.005029,0.0,4.0,4.0,1.0,1.0,0.010337,0.0,0.0,0.0,0.0
2020-01-31,0.011938,0.006281,0.0,6.0,2.0,1.0,0.0,0.023356,0.0,0.0,0.0,0.0
2020-02-01,0.011938,0.006281,0.0,6.0,0.0,1.0,0.0,0.023356,0.0,0.0,0.0,0.0
2020-02-02,0.014224,0.010048,0.0,10.0,4.0,2.0,1.0,0.028928,0.0,0.0,0.0,0.0
2020-02-03,0.014224,0.010048,0.0,88.0,78.0,2.0,0.0,0.028928,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-02,0.000000,0.000000,0.0,102855048.0,0.0,205288.0,0.0,0.041225,0.0,0.0,0.0,0.0
2022-09-03,0.000000,0.000000,0.0,102855048.0,0.0,205288.0,0.0,0.041225,0.0,0.0,0.0,0.0
2022-09-04,0.000000,0.000000,0.0,102855048.0,0.0,205288.0,0.0,0.041225,0.0,0.0,0.0,0.0
2022-09-05,0.000000,0.000000,0.0,102855048.0,0.0,205288.0,0.0,0.041225,0.0,0.0,0.0,0.0
2022-09-06,0.000000,0.000000,0.0,102855048.0,0.0,205288.0,0.0,0.041225,0.0,0.0,0.0,0.0

In [116]:
 
country_index_United_Kingdom.to_csv('../raw_data/out_csv/index_UK.csv')

In [117]:

country_indicator_United_Kingdom.to_csv('../raw_data/out_csv/indicator_UK.csv')