In [6]:
import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.express as px
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [29]:
 #sklearn preproc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer, make_column_transformer, make_column_selector
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import RobustScaler, OneHotEncoder, OrdinalEncoder
from sklearn.metrics import make_scorer

from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import RandomForestRegressor

In [30]:
data_index=df_index=pd.read_csv('./usa_index.csv')

In [14]:
data_index.head()

,date,containment_and_health,stringency,economics_sup,total_cases,new_cases,total_deaths,new_deaths,gov_response,country_code,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred
0,2020-01-01,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN
1,2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [39]:
data_index[data_index['total_deaths']>0]

,date,containment_and_health,stringency,economics_sup,total_cases,new_cases,total_deaths,new_deaths,gov_response,country_code,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred
21,2020-01-22,328.45,27.80,0.0,2.0,2.0,1.0,1.0,287.55,NaN,NaN,NaN,NaN
22,2020-01-23,332.02,33.36,0.0,2.0,0.0,1.0,0.0,290.67,NaN,NaN,NaN,NaN
23,2020-01-24,344.52,52.82,0.0,4.0,2.0,1.0,0.0,301.59,NaN,NaN,NaN,NaN
24,2020-01-25,344.52,52.82,0.0,4.0,0.0,1.0,0.0,301.59,NaN,NaN,NaN,NaN
25,2020-01-26,350.47,62.08,0.0,10.0,6.0,1.0,0.0,306.79,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125890,2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,TUR,68.32,62.70,48.39
125891,2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,USA,79.25,67.58,39.50
125892,2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,OWID_UMC,83.89,79.24,48.09
125893,2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,URY,87.58,84.42,82.84
125894,2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,OWID_WRL,67.72,62.29,30.90

In [15]:
data_indicator=df_index=pd.read_csv('./usa_indicator.csv')

In [16]:
data_indicator.head()

,date,cancel_public_events,restrictions_on_gathering,close_public_transport,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,income_support,debt/contract_relief,public_information_campaigns,...,protection_of_elderly_people,total_cases,new_cases,total_deaths,new_deaths,workplace_closing,country_code,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred
0,2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN
1,2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [41]:
data_index=data_index.set_index('date')

In [42]:
data_index.index

Index(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04', '2020-01-05',
       '2020-01-06', '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
       ...
       '2022-09-08', '2022-09-08', '2022-09-08', '2022-09-08', '2022-09-08',
       '2022-09-08', '2022-09-08', '2022-09-08', '2022-09-08', '2022-09-08'],
      dtype='object', name='date', length=125982)

In [43]:
data_index.index=pd.to_datetime(data_index.index)

In [44]:
data_index.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2022-09-08', '2022-09-08', '2022-09-08', '2022-09-08',
               '2022-09-08', '2022-09-08', '2022-09-08', '2022-09-08',
               '2022-09-08', '2022-09-08'],
              dtype='datetime64[ns]', name='date', length=125982, freq=None)

In [45]:
data_index[data_index['total_deaths']>0]

,containment_and_health,stringency,economics_sup,total_cases,new_cases,total_deaths,new_deaths,gov_response,country_code,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred
date,,,,,,,,,,,,
2020-01-22,328.45,27.80,0.0,2.0,2.0,1.0,1.0,287.55,NaN,NaN,NaN,NaN
2020-01-23,332.02,33.36,0.0,2.0,0.0,1.0,0.0,290.67,NaN,NaN,NaN,NaN
2020-01-24,344.52,52.82,0.0,4.0,2.0,1.0,0.0,301.59,NaN,NaN,NaN,NaN
2020-01-25,344.52,52.82,0.0,4.0,0.0,1.0,0.0,301.59,NaN,NaN,NaN,NaN
2020-01-26,350.47,62.08,0.0,10.0,6.0,1.0,0.0,306.79,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,TUR,68.32,62.70,48.39
2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,USA,79.25,67.58,39.50
2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,OWID_UMC,83.89,79.24,48.09
2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,URY,87.58,84.42,82.84
2022-09-06,0.00,0.00,0.0,188761844.0,258013.0,2090809.0,1242.0,2146.68,OWID_WRL,67.72,62.29,30.90

In [25]:
data_index[~(data_index.index < '2020-01-22')]

,containment_and_health,stringency,economics_sup,total_cases,new_cases,total_deaths,new_deaths,gov_response,country_code,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred
date,,,,,,,,,,,,
2020-01-22,328.45,27.80,0.0,2.0,2.0,1.0,1.0,287.55,NaN,NaN,NaN,NaN
2020-01-23,332.02,33.36,0.0,2.0,0.0,1.0,0.0,290.67,NaN,NaN,NaN,NaN
2020-01-24,344.52,52.82,0.0,4.0,2.0,1.0,0.0,301.59,NaN,NaN,NaN,NaN
2020-01-25,344.52,52.82,0.0,4.0,0.0,1.0,0.0,301.59,NaN,NaN,NaN,NaN
2020-01-26,350.47,62.08,0.0,10.0,6.0,1.0,0.0,306.79,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-08,0.00,0.00,0.0,103838653.0,0.0,0.0,0.0,2146.68,THA,79.55,74.59,44.42
2022-09-08,0.00,0.00,0.0,103838653.0,0.0,0.0,0.0,2146.68,TUR,68.32,62.70,48.43
2022-09-08,0.00,0.00,0.0,103838653.0,0.0,0.0,0.0,2146.68,OWID_UMC,83.94,79.34,48.24
2022-09-08,0.00,0.00,0.0,103838653.0,0.0,0.0,0.0,2146.68,URY,87.58,84.42,82.86
2022-09-08,0.00,0.00,0.0,103838653.0,0.0,0.0,0.0,2146.68,OWID_WRL,67.74,62.32,31.02

In [28]:
data_index['day-2'] = data_index['total_deaths'].shift(periods=2)